'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SALESANDINVENTORYSYSTEM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1683043685638() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1683043685638", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _416_4169142_helpful_clip_art() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("416-4169142_helpful-clip-art", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _416_4169142_helpful_clip_art1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("416-4169142_helpful-clip-art1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _433_4333068_hover_icon_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("433-4333068_hover-icon-png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _433_4333068_hover_icon_png1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("433-4333068_hover-icon-png1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _CITYPNG_COM_White_Circle_Round_Question_Mark_Icon_PNG___1124x1124() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("[CITYPNG.COM]White Circle Round Question Mark Icon PNG - 1124x1124", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property admin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("admin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clipart2399764() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipart2399764", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clipart23997641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipart23997641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_cloud_backup_restore_100__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-cloud-backup-restore-100 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_processing20190919_3788_cuf3o4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_processing20190919-3788-cuf3o4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_processing20210910_19574_1qoobzd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_processing20210910-19574-1qoobzd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_processing20210910_19574_1qoobzd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_processing20210910-19574-1qoobzd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lv_0_20230503003934() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lv_0_20230503003934", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Media_230503_005719() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Media_230503_005719", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noun_data_backup_4550589() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noun-data-backup-4550589", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noun_data_backup_45505891() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noun-data-backup-45505891", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noun_data_backup_45505892() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noun-data-backup-45505892", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noun_restore_down_1387364() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noun-restore-down-1387364", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_4_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag-4-24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_4_241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag-4-241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tags() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tags", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toppng_com_telephone_symbol_white_white_contact_icon_1776x1890() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toppng.com-telephone-symbol-white-white-contact-icon-1776x1890", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toppng_com_white_envelope_icon_envelope_icon_white_464x338() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toppng.com-white-envelope-icon-envelope-icon-white-464x338", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toppng1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toppng1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vector_Facebook_Logo_Black_And_White_PNG_Picture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vector-Facebook-Logo-Black-And-White-PNG-Picture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_mark_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-mark-24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_mark_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-mark-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_mark_64__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-mark-64 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_symbol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-symbol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
